GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/users

###

GET http://localhost:3003/api/blogs/6409e8f147dd491d1a027252

###
GET http://localhost:3003/api/blogs/641b47caa82bf2b5d92fca26

###
GET http://localhost:3003/api/blogs/642d78dd752941f2f6aea37e
