POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test title",
    "author": "test author",
    "url": "test url",
    "likes": "993"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "likes": "2"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "coconut89",
    "password": "adsfpoihadpfnakjehk",
    "name": "Chet Baker"
}