PUT http://localhost:3003/api/blogs/642d78dd752941f2f6aea37e
Content-Type: application/json

{
  "title": "Fullstack Development 2",
  "author": "Matthew Horn",
  "url": "notaurl2",
  "likes": 1233,
  "user": "642d7893752941f2f6aea377"
  }
